name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 2.2
            gemfile: "gemfiles/rails_5_0.gemfile"
          - ruby: 2.2
            gemfile: "gemfiles/rails_5_1.gemfile"
          - ruby: 2.3
            gemfile: "gemfiles/rails_5_0.gemfile"
          - ruby: 2.3
            gemfile: "gemfiles/rails_5_1.gemfile"
          - ruby: 2.4
            gemfile: "gemfiles/rails_5_0.gemfile"
          - ruby: 2.4
            gemfile: "gemfiles/rails_5_1.gemfile"
          - ruby: 2.4
            gemfile: "gemfiles/rails_5_2.gemfile"
          - ruby: 2.5
            gemfile: "gemfiles/rails_5_0.gemfile"
          - ruby: 2.5
            gemfile: "gemfiles/rails_5_1.gemfile"
          - ruby: 2.5
            gemfile: "gemfiles/rails_5_2.gemfile"
          - ruby: 2.5
            gemfile: "gemfiles/rails_6_0.gemfile"
          - ruby: 2.5
            gemfile: "gemfiles/rails_6_1.gemfile"
          - ruby: 2.6
            gemfile: "gemfiles/rails_5_0.gemfile"
          - ruby: 2.6
            gemfile: "gemfiles/rails_5_1.gemfile"
          - ruby: 2.6
            gemfile: "gemfiles/rails_5_2.gemfile"
          - ruby: 2.6
            gemfile: "gemfiles/rails_6_0.gemfile"
          - ruby: 2.6
            gemfile: "gemfiles/rails_6_1.gemfile"
          - ruby: 2.7
            gemfile: "gemfiles/rails_6_0.gemfile"
          - ruby: 2.7
            gemfile: "gemfiles/rails_6_1.gemfile"
          - ruby: 2.7
            gemfile: "gemfiles/rails_head.gemfile"
          - ruby: 3.0
            gemfile: "gemfiles/rails_6_1.gemfile"
          - ruby: 3.0
            gemfile: "gemfiles/rails_head.gemfile"
            allow-failure: true
          - ruby: head
            gemfile: "gemfiles/rails_head.gemfile"
            allow-failure: true
          - ruby: head
            gemfile: "gemfiles/rails_head.gemfile"
            allow-failure: true
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3